apiVersion: apps/v1
kind: Deployment
metadata:
  name: trinbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trinbuggy
  template:
    metadata:
      labels:
        app: trinbuggy
    spec:
      containers:
      - name: trinbuggy
        image: 767397800495.dkr.ecr.us-east-2.amazonaws.com/trin
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trinbuggy
    k8s-app: tringbuggy
  name: trinbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: trinbuggy
